name: Mypy Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # at 4 am
    - cron:  '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    env:
      src: "mltb2"
      other-src: "tests setup.py docs"

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3

    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[checking,optional]

    - name: Check with mypy
      run: mypy --install-types --non-interactive ${{ env.src }} ${{ env.other-src }}
